### ISSUE TITLE
number of iterations

### ISSUE THREAD

**Issue by YangSiri** [DrGabor/MiNoM#1]
Hi, @DrGabor 

Thanks for the great work you've done. I'm trying to model my residuals but get invalid distribution. The posterior of every residual is above 1. Do you have some advice that I need to pay attention to? What ranges are the sita and coeff parameters? I'm also curious about the max iterations of EM and IRLS. Do you have tips on this?

example of the distribution:
![图片](https://user-images.githubusercontent.com/33154113/82968839-ca23a800-a000-11ea-9f3e-f4d0368795a0.png)

Looking forward to your help ;)

**Comment by DrGabor** [comment]
Hi @YangSiri, 

Thanks for your appreciation. It is sort of weid that the posterior is larger than 1.0. By definition of Bayesian rule, the posterior p(z|x) = p(x, z) / \sum_z( p(x, z) ) is smaller than 1.0 owing to the normalized coefficient \sum_z( p(x, z). 

Do you use Gaussian mixture model (GMM) to model the residual errors? There exists one issue you really need to deal with: if the residuals are (1000, 1010, 1020), the posterior needs evaluate the formula like exp(-1000) / ( exp(-1000) + exp(-1010) + exp(-1020) ), which is numerically instable since exp(-1000) is nearly infinitely small. Thus you should convert it to 
 exp(-1000 + 1000) / ( exp(-1000+1000) + exp(-1010+1000) + exp(-1020+1000) ) for numerically stability. 

The range of sita has no limitations, and the coefficient lies between 0 and 1. 

As for the EM and IRLS iterations, I found that the EM iteration can be less than 10, and IRLS can be 10~100. Larger EM iteration will make the algorithm pre-maturely stuck into local minima. In a word, you need keep in mind that tradeoff should be achieved between EM and IRLS.

The residual picture you presented seems to be ill-conditioned and cannot be properly modeled by mixture models, can you tell me where did it come from? It seems that the model parameters are far from ground truth, and thus EM parameters are meaningless. You need alternately 1) update model parameters and 2) update EM parameters. After several iterations, the residuals will become proper to be modeled via GMM.

**Comment by YangSiri** [comment]
Thanks for your generous advice, @DrGabor 

The posterior i mean is the _probSum_ in your code which i think is 1xn. 

I didn't use the GMM and the residual is from point-to-plane metric. It seems to follow the ep distribution from the picture(red hist). The model shape priors is [1.0, 2.0], and sometimes the value of sita and coeff become nan. I must've done sth wrong in the process. 

And i wonder is there any way to tune the iterations.

**Comment by DrGabor** [comment]
Hi @YangSiri, 

The Prob_Sum is the normalized coefficient, and it can be larger than 1.0. Z is just the posterior and it lies in between 0.0 and 1.0. 

If possible, you can send me the sample data and I will check where the problem is. Sometimes EM algorithm will have the over-fitting problem, which means one component in mixture model collapses into one specific data point, and thus other components are diminished. But overfitting is rare to be presented as far as I know.

**Comment by YangSiri** [comment]
Yes, @DrGabor 

Should the distribution of _probSum_ follow the same shape as distribution of errors? Isn't Z supposed to be the latent variables? 

I'm sorry the data can't be sent. Can i just give you the residuals file?

**Comment by DrGabor** [comment]
Hi @YangSiri , 

The answer is not because probSum is just the normalized coefficient, and the residual error distribution (RED) is only related to the weight and variance in GMM. I'd be appreciated to receive the residuals file.

**Comment by YangSiri** [comment]
Yes, @DrGabor 

Thanks for your patience, but your model is mixtures of ep instead of gaussian, right?
Then how can i check the modeling effect(the first pic in your paper)?

[residuals.zip](https://github.com/DrGabor/MiNoM/files/4686300/residuals.zip)

**Comment by DrGabor** [comment]
Hi @YangSiri, 

Can you download the DrGabor/MiNoM again? Then running the testRED.m, you will see the mixture model fitting results.

**Comment by YangSiri** [comment]
Yes, @DrGabor 

I actually reimplemented in C++ myself.

**Comment by DrGabor** [comment]
Hi @YangSiri, 

I should say that [1.0 2.0] indeed generates accurate results, but it seems a little instable. Gaussian mixture model is stable, but the results are less accurate. If you can find out the solution, let me know. I think the selection of shape vector is still an open problem.

**Comment by YangSiri** [comment]
Yes, @DrGabor 

Thank you very much for your help. But would you like to show me the reason why it cant be estimated together with sita?

And can you show me the result you tested?

**Comment by DrGabor** [comment]
Hi @YangSiri, 

My original idea of modeling the RED via mixture model is inspired by Prof. Deyu Meng in Xi'an Jiaotong University. In his work, the shape vector is also specified by users. I assume the underlying reason is that seeking the optimal shape vector is computational infeasible and more of a combinatorial optimization problem, while human-specified shape vector already exhibits satisfying performance. 

I'd appreciate your idea of automatically determining the shape vector, which is mostly equivalent to the problem of determining the number of components or K in GMM. Determining K had ready covered in the previous work of Prof. Deyu Meng. Maybe you can derive a flexible GMM version of scan matching, which is promising to be both accurate and numerically stable than MiNoM. 

The result of shape vector selection is still under review, I am sorry that I cannot show you the result.

**Comment by YangSiri** [comment]
Yes, @DrGabor 

Thanks for your sharing. I meant the result pic of my data ;)

**Comment by DrGabor** [comment]
Hi @YangSiri, 

You can see the result pic of your data by running test.m. I newly upload some m files into the repository.

**Comment by YangSiri** [comment]
Yes, @DrGabor 

I saw the code. Thanks for your generous help! The problem is i dont have a matlab. I'm asking you to just show me the pic or the model parameters, lol

**Comment by DrGabor** [comment]
The pic of residuals/10.txt, s = [1.0 2.0], maxIter_em = 10. 

Model(1) =      
type: 'ep'
     para: 6.8509
    prior: 1
    coeff: 0.4947

Model(2) = 
     type: 'ep'
     para: 23.2691
    prior: 2
    coeff: 0.5053

![RED](https://user-images.githubusercontent.com/35476470/82979338-60fc5e80-a019-11ea-979c-524a35a875be.png)

**Comment by YangSiri** [comment]
Great, @DrGabor 

Thanks again for you help.
